# Generated by Django 5.2.3 on 2025-06-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_availability_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='triage_status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('in_consultation', 'In Consultation'), ('done', 'Done'), ('no_show', 'No-show')], default='waiting', max_length=20, null=True),
        ),
    ]
