# Generated by Django 5.2.3 on 2025-07-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_doctorprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
