# Generated by Django 5.2.3 on 2025-07-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_doctorprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='repeat',
            field=models.CharField(choices=[('none', 'None'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='availability',
            name='repeat_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
