# Generated by Django 5.2.3 on 2025-07-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_availability_repeat_availability_repeat_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available_on_call',
            field=models.BooleanField(default=False),
        ),
    ]
