# Generated by Django 5.2 on 2025-07-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_notification_doctor_notification_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(default="appointment", max_length=50),
            preserve_default=False,
        ),
    ]
